# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'AbominationBattler iOS' do
pod ‘Mixpanel’

end

target 'AbominationBattler Android' do

end

target 'AbominationBattler Mac' do

end

